### ISSUE TITLE
Bug on pins above 7, error on lines 103 and 104, missing the (i, ...

### ISSUE THREAD

**Issue by TaylorAvila** [sakabug/Bugtton#3]
Hello brother, your library is very useful to me, but it has a bug in pins above 7, I found the error I believe to be a typo on lines 103 and 104 of the .cpp file, thanks for your code and keep up the good Work

**Comment by sakabug** [comment]
**Thanks.**

I put v1.0.4 out. Should update in IDE in few hours.
