### ISSUE TITLE
Distinguishing between long and short press

### ISSUE THREAD

**Issue by ICYou** [sakabug/Bugtton#4]
I'm creating a stopwatch timer that starts/pauses/resumes upon press. This is triggered on button rose.
To reset the timer, the button is to be longpressed. This is triggered on buttons.helduntil(1,2000);

After pressing and holding the button for 2 sec, it resets, when releasing the button, it also triggers the button rose, starting the timer again.

Is there a way to efficiently do this with this library?

`  bool button1LongPress = buttons.heldUntil(1, 2000);
  
  if(button1LongPress){
    Serial.println("Button longpressed");
    timerStart = false;
    startTime = 0;
    shotTime = 0;
    timerPaused = false;
  }else if(buttons.rose(1) && !button1LongPress){
    Serial.println("button rose");
    
    if (!timerStart){ //if timer has not started, start
      timerStart = true;
      Serial.println("timer started");
    
    }else if(timerPaused){ // if paused, unpause
      startTime = millis() - shotTime;
      timerPaused = false;
      Serial.println("timer paused");
    
    }else{ // if started, pause
      timerPaused = true;
      Serial.println("timer resumed");
    }
  }`

**Comment by sakabug** [comment]
Well, yes, releasing button will trigger rose.

You could make a flag that gets true value after buttons.heldUntil(1, 2000) returns true, and reset it to false at the end of if(button.rose(1))

```
if(button.rose(1))
{
    if (!flag) actions;
    flag = false;
}

```
That way it would skip any actions on button.rose(1) ONCE after your long press.

**Comment by ICYou** [comment]
Ah right!
That seems like an elegant solution. Just skip the button rose once.

Thank you!!
