### ISSUE TITLE
Wrong datatype in Bugtton::Bugtton(const uint8_t a, const uint8_t *b, uint8_t dt)

### ISSUE THREAD

**Issue by Pixopax** [sakabug/Bugtton#6]
Since we can define button pins als negative to give them a pulldown on the port we need type int8_t for he buttons:

Bugtton::Bugtton(const uint8_t a, const int8_t *b, uint8_t dt)
istead of 
Bugtton::Bugtton(const uint8_t a, const uint8_t *b, uint8_t dt)

Same in the header file:
Bugtton(const uint8_t a, const int8_t *b, uint8_t dt);
instead of
Bugtton(const uint8_t a, const uint8_t *b, uint8_t dt);

**Comment by sakabug** [comment]
Oh my, I had left it half way while implementing. Will update to IDE in few hours.

**Comment by Pixopax** [comment]
Thanks!
