### ISSUE TITLE
held() and up() returning a stuck value

### ISSUE THREAD

**Issue by sonik-br** [sakabug/Bugtton#7]
Hi,

The `held()` and `up()` functions can sometimes return a stuck value that not represents the current pin state.

Test code:
```
#include <Bugtton.h>

#define PIN_BTN 7

const uint8_t debounceTime = 2;
const uint8_t buttonCount = 1;
const uint8_t buttonPins[buttonCount] = { PIN_BTN };
Bugtton btnDebounce(buttonCount, buttonPins, debounceTime);

void setup() {
  Serial.begin(115200);
}

void loop() {
  btnDebounce.update();

  if(btnDebounce.held(0))
    Serial.print(F("HELD : "));
  else
    Serial.print(F("UP   : "));
  
  Serial.println(digitalRead(PIN_BTN));
}
```

Result log:
[log.txt](https://github.com/sakabug/Bugtton/files/10207897/log.txt)

See that last lines of the log it shows as `HELD : 1`
I had to press and release a the button a few times until it returned the correct value.

**Comment by sakabug** [comment]
Sorry, had family addition in late 2022, been off from arduinos.

Any update on the issue? There's the printBIN() function in .cpp which you can add the line in any part of the librarys' code to debug issue further. I can look the issue, but takes few months (waiting for toddler go to daycare).

**Comment by sonik-br** [comment]
Thanks for the reply.

I could not find the cause and I'm not using the lib anymore.
Moved most of my projects to rp2040 :)
